import streamlit as st
import pandas as pd
import json
from llm_chain import analyze_emails

# === Save CSV ===
def save_results_to_csv(category, location):
    with open("complaint_analysis_results.csv", "w", newline="") as f:
        f.write("Most Complained Product,Most Complained Location\n")
        f.write(f"{category},{location}\n")

# === Sentiment Mock Analyzer ===
def tag_complaint_sentiment(text):
    keywords = ["poor", "bad", "broke", "terrible", "hate", "leaks", "worst"]
    if any(k in text.lower() for k in keywords):
        return "🔴 Negative"
    return "🟢 Positive"

# === Summary Generator ===
def generate_summary(category, location):
    return f"""
📨 **Complaint Summary Report**

Over the past period, complaints have shown a significant trend.

🛍️ **Most frequent product complaints** were about **{category}** items.  
📍 **Most affected store location** appears to be **{location}**.

Recommendations:
- Investigate supply issues with {category}
- Review service quality at {location}

Report generated by 🤖 AI-powered analyzer.
    """

# === Streamlit App ===
st.set_page_config(page_title="GrievanceGrid", layout="centered")
st.title("📬 GrievanceGrid")

input_mode = st.radio("Choose input method:", ["📁 Upload JSON", "📝 Paste Manually"])
emails = []

# === Upload JSON ===
if input_mode == "📁 Upload JSON":
    uploaded_file = st.file_uploader("Upload complaints JSON", type=["json"])
    if uploaded_file:
        try:
            data = json.load(uploaded_file)
            if isinstance(data, list):
                emails = [str(item).strip() for item in data if isinstance(item, str) and item.strip()]
                st.success(f"✅ Loaded {len(emails)} complaints.")
            else:
                st.error("❌ JSON must be a list of strings.")
        except Exception as e:
            st.error("❌ Could not read the file.")
            st.exception(e)

# === Paste Manually ===
elif input_mode == "📝 Paste Manually":
    user_input = st.text_area("Paste complaints here (one per line)", height=200)
    if user_input.strip():
        emails = [line.strip() for line in user_input.strip().split("\n") if line.strip()]

# === Analyze Complaints ===
if emails and st.button("🔍 Analyze Complaints", key="analyze_button"):
    with st.spinner("💡 Thinking... analyzing complaints..."):
        try:
            result = analyze_emails(emails)
            st.success("🎉 Analysis complete!")

            # === Parse Output with fallback
            lines = result.split("\n")
            category = lines[0].split(" is ")[-1].strip(".").strip() if len(lines) > 0 else "Unknown"
            location = lines[1].split(" is ")[-1].strip(".").strip() if len(lines) > 1 else "Unknown"

            if not category:
                category = "Unknown"
            if not location:
                location = "Unknown"

            # 🎯 Display Key Insights
            st.markdown("### 🔍 Key Insights")
            st.markdown(f"🛍️ **Most Complained Product:** `{category}`")
            st.markdown(f"📍 **Most Complained Location:** `{location}`")

            # 📊 Bar Chart based on actual frequency
            product_keywords = ["shirt", "clothing", "shoes", "phone", "tv", "refrigerator"]
            location_keywords = ["dallas", "new york", "chicago", "la", "los angeles"]

            product_count = sum(any(p in e.lower() for p in product_keywords) for e in emails)
            location_count = sum(any(l in e.lower() for l in location_keywords) for e in emails)

            chart_data = pd.DataFrame({
                "Target": ["Product", "Location"],
                "Complaints": [product_count, location_count]
            })
            st.bar_chart(chart_data.set_index("Target"))

            # 💬 Complaint Table with Sentiment
            st.markdown("### 🧾 All Complaints with Sentiment")
            complaint_data = pd.DataFrame({
                "Complaint": emails,
                "Sentiment": [tag_complaint_sentiment(e) for e in emails]
            })
            st.dataframe(complaint_data, use_container_width=True)

            # 📝 Generate Summary Report
            with st.expander("📄 View AI Summary Report"):
                st.markdown(generate_summary(category, location))

            # 💾 Save to CSV + Download
            save_results_to_csv(category, location)
            with open("complaint_analysis_results.csv", "rb") as f:
                st.download_button("⬇️ Download CSV Report", f, file_name="complaint_analysis_results.csv")

            # 🎉 Confetti
            st.balloons()

        except Exception as e:
            st.error("⚠️ Something went wrong.")
            st.exception(e)

elif st.button("🔍 Analyze Complaints", key="empty_warning_button") and not emails:
    st.warning("Please provide some complaints first.")
